version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2020 SOFA GmbH <CAD@cadability.de>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "CADability/netDxf/**"
SPDX-FileCopyrightText = "2019-2023 Daniel Carvajal <haplokuon@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
SPDX-FileCopyrightText = "2004-2005 Peter Golde, Wintellect"
SPDX-License-Identifier = "EPL-1.0"
path = [
	"CADability/Algorithms.cs",
	"CADability/Bag.cs",
	"CADability/CollectionBase.cs",
	"CADability/Comparers.cs",
	"CADability/Hash.cs",
	"CADability/ListBase.cs",
	"CADability/MultiDictionaryBase.cs",
	"CADability/OrderedMultiDictionary.cs",
	"CADability/Pair.cs",
	"CADability/ReadOnlyCollectionBase.cs",
	"CADability/RedBlack.cs",
	"CADability/Set.cs",
	"CADability/Strings.cs",
	"CADability/Util.cs",
]
